spring:
    application:
        name: graphql-learning

    datasource:
        url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true
#        url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=true&requireSSL=true
        username: ${MYSQLUSER}
        password: ${MYSQLPASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update   # dev only
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    graphql:
        path: /graphql
        graphiql:
            enabled: true

logging:
    level:
        org.hibernate.SQL: DEBUG

jwt:
    secret: VERY_LONG_SECRET_KEY_CHANGE_THIS_IN_PROD

server:
    port: ${PORT:8080}